/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: ["./src/**/*.{js,jsx,ts,tsx}", "./public/index.html"],
  theme: {
    extend: {
      colors: {
        page: "var(--color-page)",
        "page-secondary": "var(--color-page-secondary)",
        surface: "var(--color-surface)",
        "surface-raised": "var(--color-surface-raised)",
        "surface-muted": "var(--color-surface-muted)",
        glass: "var(--color-surface-glass)",
        neumorphic: "var(--color-surface-neumorphic)",
        overlay: "var(--color-overlay)",
        "text-primary": "var(--color-text-primary)",
        "text-secondary": "var(--color-text-secondary)",
        "text-muted": "var(--color-text-muted)",
        "text-inverse": "var(--color-text-inverse)",
        "text-accent": "var(--color-text-accent)",
        "border-default": "var(--color-border)",
        "border-strong": "var(--color-border-strong)",
        "border-glass": "var(--color-border-glass)",
        "brand-primary": "var(--color-brand-primary)",
        "brand-secondary": "var(--color-brand-secondary)",
        "brand-accent": "var(--color-brand-accent)",
        success: "var(--color-success)",
        warning: "var(--color-warning)",
        error: "var(--color-error)",
        info: "var(--color-info)",
        /* Compatibility aliases retained for existing pages during migration. */
        primary: "var(--color-brand-primary)",
        secondary: "var(--color-page-secondary)",
        accent: "var(--color-brand-accent)",
        background: "var(--color-page)",
        card: "var(--color-surface)",
        border: "var(--color-border)",
        textPrimary: "var(--color-text-primary)",
        textSecondary: "var(--color-text-secondary)",
      },
      fontFamily: {
        sans: ['"Inter"', '"Segoe UI"', "system-ui", "-apple-system", "sans-serif"],
        display: ['"Inter"', '"Segoe UI"', "system-ui", "-apple-system", "sans-serif"],
      },
      boxShadow: {
        xs: "var(--shadow-xs)",
        sm: "var(--shadow-sm)",
        md: "var(--shadow-md)",
        lg: "var(--shadow-lg)",
        glass: "var(--shadow-glass)",
        neumorphic: "var(--shadow-neumorphic-raised)",
        "neumorphic-pressed": "var(--shadow-neumorphic-pressed)",
        glow: "var(--shadow-glow)",
        premium: "var(--shadow-lg)",
        card: "var(--shadow-md)",
        "glow-accent": "var(--shadow-glow)",
      },
      borderRadius: {
        sm: "var(--radius-sm)",
        md: "var(--radius-md)",
        lg: "var(--radius-lg)",
        xl: "var(--radius-xl)",
        "2xl": "var(--radius-2xl)",
        pill: "var(--radius-pill)",
      },
      transitionDuration: {
        fast: "var(--duration-fast)",
        normal: "var(--duration-normal)",
        slow: "var(--duration-slow)",
      },
      transitionTimingFunction: {
        standard: "var(--ease-standard)",
        emphasized: "var(--ease-emphasized)",
        spring: "var(--ease-spring)",
      },
      zIndex: {
        dropdown: "100",
        sticky: "200",
        drawer: "400",
        modal: "500",
        toast: "600",
      },
      backgroundImage: {
        "brand-gradient": "var(--gradient-brand)",
        "brand-soft": "var(--gradient-brand-soft)",
        "hero-gradient": "var(--gradient-hero)",
        "surface-gradient": "var(--gradient-surface)",
        "glass-gradient": "var(--gradient-surface)",
        "button-gradient": "var(--gradient-brand)",
      },
      keyframes: {
        shimmer: {
          "0%": { backgroundPosition: "200% 0" },
          "100%": { backgroundPosition: "-200% 0" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-8px)" },
        },
        "soft-pulse": {
          "0%, 100%": { opacity: "0.58" },
          "50%": { opacity: "0.82" },
        },
      },
      animation: {
        shimmer: "shimmer 1.8s var(--ease-standard) infinite",
        float: "float 7s var(--ease-standard) infinite",
        "soft-pulse": "soft-pulse 2s var(--ease-standard) infinite",
      },
    },
  },
  plugins: [],
};
