import React, { useEffect, useMemo, useState } from "react";
import { FiArrowUpRight, FiBox, FiShoppingBag, FiUsers } from "react-icons/fi";
import { Link } from "react-router-dom";
import { getAdminOverview } from "../features/admin/AdminApi";
import { formatPrice } from "../utils/currencyFormatter";

const panel = "rounded-xl border border-[#e3ddd3] bg-white shadow-[0_8px_30px_rgba(32,28,20,.035)]";
const statusColor = { delivered: "bg-emerald-50 text-emerald-700", cancelled: "bg-red-50 text-red-600", shipped: "bg-slate-100 text-slate-700", processing: "bg-amber-50 text-amber-700", pending: "bg-amber-50 text-amber-700", confirmed: "bg-blue-50 text-blue-700", packed: "bg-indigo-50 text-indigo-700", out_for_delivery: "bg-cyan-50 text-cyan-700" };

export const AdminOverviewPage = () => {
  const [data, setData] = useState(null);
  const [error, setError] = useState("");
  useEffect(() => { getAdminOverview().then(setData).catch((value) => setError(value?.message || "Dashboard data is unavailable.")); }, []);
  const metrics = useMemo(() => [
    { label: "Revenue", value: formatPrice(data?.totalSales || 0), icon: FiArrowUpRight, note: "Confirmed store sales" },
    { label: "Orders", value: Number(data?.totalOrders || 0).toLocaleString("en-IN"), icon: FiShoppingBag, note: "Across all statuses" },
    { label: "Customers", value: Number(data?.totalUsers || 0).toLocaleString("en-IN"), icon: FiUsers, note: "Registered accounts" },
    { label: "Products", value: Number(data?.totalProducts || 0).toLocaleString("en-IN"), icon: FiBox, note: `${data?.lowStockProducts?.length || 0} need attention` },
  ], [data]);
  const statusRows = data?.orderStatusBreakdown || [];
  const totalStatuses = statusRows.reduce((sum, row) => sum + row.count, 0) || 1;

  return <div className="space-y-5">
    <div><p className="text-sm font-medium text-[#777b83]">Here’s what’s happening with your store today.</p><h1 className="mt-1 text-3xl font-bold tracking-[-.04em]">Overview</h1></div>
    {error ? <p className="rounded-xl border border-red-200 bg-red-50 p-4 text-sm text-red-700">{error}</p> : null}
    <section className="grid gap-3 sm:grid-cols-2 xl:grid-cols-4">{metrics.map(({ label, value, icon: Icon, note }) => <article key={label} className={`${panel} flex items-center gap-4 p-5`}><span className="grid h-12 w-12 shrink-0 place-items-center rounded-full bg-[#f6efe4] text-xl text-[#a77724]"><Icon /></span><div><p className="text-sm font-semibold">{label}</p><strong className="mt-1 block text-2xl tracking-tight">{value}</strong><span className="text-xs text-[#7a7d84]">{note}</span></div></article>)}</section>
    <section className="grid gap-4 xl:grid-cols-[1.65fr_.75fr]">
      <div className={`${panel} p-5`}><div className="flex items-center justify-between"><div><h2 className="font-bold">Revenue overview</h2><p className="mt-1 text-xs text-[#7a7d84]">Store performance snapshot</p></div><span className="rounded-lg border border-[#e3ddd3] px-3 py-2 text-xs">Last 6 months</span></div><div className="mt-7 h-[230px] overflow-hidden rounded-lg bg-[linear-gradient(#fff,#fdfaf4)]"><svg viewBox="0 0 800 230" className="h-full w-full" role="img" aria-label="Revenue trend"><defs><linearGradient id="adminChart" x1="0" y1="0" x2="0" y2="1"><stop offset="0" stopColor="#c18b2e" stopOpacity=".22"/><stop offset="1" stopColor="#c18b2e" stopOpacity="0"/></linearGradient></defs>{[40,85,130,175].map((y)=><line key={y} x1="30" x2="780" y1={y} y2={y} stroke="#ebe6dc" strokeWidth="1"/>)}<path d="M35 180 C120 158 150 145 220 136 S340 68 420 108 S535 48 610 84 S720 56 775 70 L775 215 L35 215 Z" fill="url(#adminChart)"/><path d="M35 180 C120 158 150 145 220 136 S340 68 420 108 S535 48 610 84 S720 56 775 70" fill="none" stroke="#b47d22" strokeWidth="4" strokeLinecap="round"/></svg></div></div>
      <div className={`${panel} p-5`}><h2 className="font-bold">Order status</h2><div className="mt-6 flex items-center justify-center"><div className="grid h-32 w-32 place-items-center rounded-full bg-[conic-gradient(#26734a_0_52%,#c18b2e_52%_76%,#4b5563_76%_92%,#d44a45_92%)]"><div className="grid h-20 w-20 place-items-center rounded-full bg-white text-center"><strong className="text-xl">{data?.totalOrders || 0}</strong></div></div></div><div className="mt-6 space-y-3">{statusRows.slice(0,5).map((row)=><div key={row._id} className="flex items-center justify-between text-sm"><span className="capitalize text-[#595d65]">{String(row._id || "unknown").replaceAll("_"," ")}</span><strong>{row.count} <span className="font-normal text-[#8b8e94]">({Math.round(row.count/totalStatuses*100)}%)</span></strong></div>)}</div></div>
    </section>
    <section className="grid gap-4 xl:grid-cols-[1.5fr_.8fr]">
      <div className={`${panel} overflow-hidden`}><div className="flex items-center justify-between border-b border-[#ece7df] px-5 py-4"><h2 className="font-bold">Recent orders</h2><Link to="/admin/orders" className="text-sm font-semibold text-[#a77724]">View all</Link></div><div className="overflow-x-auto"><table className="min-w-full text-left text-sm"><thead className="bg-[#fcfaf6] text-xs text-[#74777e]"><tr><th className="px-5 py-3">Order</th><th className="px-5 py-3">Customer</th><th className="px-5 py-3">Total</th><th className="px-5 py-3">Payment</th><th className="px-5 py-3">Status</th></tr></thead><tbody className="divide-y divide-[#eee9e1]">{data?.recentOrders?.slice(0,6).map((order)=><tr key={order._id}><td className="px-5 py-3 font-semibold">{order.orderNumber || `#${order._id.slice(-6)}`}</td><td className="px-5 py-3 text-[#64676e]">{order.addressSnapshot?.fullName || "Customer"}</td><td className="px-5 py-3 font-semibold">{formatPrice(order.pricing?.total || 0)}</td><td className="px-5 py-3 capitalize text-[#64676e]">{String(order.paymentStatus || "pending").replaceAll("_"," ")}</td><td className="px-5 py-3"><span className={`rounded-full px-2.5 py-1 text-xs font-semibold ${statusColor[order.orderStatus] || "bg-slate-100 text-slate-700"}`}>{String(order.orderStatus || "pending").replaceAll("_"," ")}</span></td></tr>)}</tbody></table></div></div>
      <div className={`${panel} p-5`}><div className="flex items-center justify-between"><h2 className="font-bold">Low stock</h2><Link to="/admin/inventory" className="text-sm font-semibold text-[#a77724]">View all</Link></div><div className="mt-4 divide-y divide-[#eee9e1]">{data?.lowStockProducts?.slice(0,6).map((product)=><div key={product._id} className="flex items-center gap-3 py-3"><img src={product.thumbnail} alt="" className="h-11 w-11 rounded-lg bg-[#f4f1eb] object-cover"/><div className="min-w-0 flex-1"><p className="truncate text-sm font-semibold">{product.name || product.title}</p><p className="text-xs text-red-600">{product.stock} left</p></div><Link to={`/admin/products/${product._id}/edit`} className="text-xs font-semibold text-[#a77724]">Restock</Link></div>)}</div></div>
    </section>
    <section className={`${panel} p-5`}><div className="flex items-center justify-between"><h2 className="font-bold">Top products</h2><Link to="/admin/products" className="text-sm font-semibold text-[#a77724]">Manage catalog</Link></div><div className="mt-4 grid gap-3 md:grid-cols-2 xl:grid-cols-3">{data?.topProducts?.slice(0,6).map((row)=><div key={row._id} className="rounded-xl bg-[#faf7f1] p-4"><p className="line-clamp-1 text-sm font-semibold">{row.name || "Product"}</p><div className="mt-3 flex items-end justify-between"><span className="text-xs text-[#777b83]">{row.units} sold</span><strong>{formatPrice(row.revenue || 0)}</strong></div></div>)}</div></section>
  </div>;
};
